### ISSUE TITLE
初始运行结果很差

### ISSUE THREAD

**Issue by xinxing277** [hellloxiaotian/ESRGCNN#11]
你好！
按照markdown文档里面的数据集和运行环境（ubuntu，python2.7）搭建起来以后，也以相同的参数运行，在同一个训练集上但是跑了多个batch，ssim和psnr都为0，这是为什么呢？
![687c3d622b4da739048c681f0975f55](https://github.com/hellloxiaotian/ESRGCNN/assets/58331146/3e16bed0-45e6-4ca0-91da-3dbb42c364ca)

**Comment by hellloxiaotian** [comment]
数据集图像没有载入成功。




祝好
田春伟 副教授
西北工业大学
















在 2023-10-25 10:59:16，"xinxing277" ***@***.***> 写道：

你好！
按照markdown文档里面的数据集和运行环境（ubuntu，python2.7）搭建起来以后，也以相同的参数运行，在同一个训练集上但是跑了多个batch，ssim和psnr都为0，这是为什么呢？

**Comment by xinxing277** [comment]
> 数据集图像没有载入成功。 祝好 田春伟 副教授 西北工业大学 在 2023-10-25 10:59:16，"xinxing277" ***@***.***> 写道： 你好！ 按照markdown文档里面的数据集和运行环境（ubuntu，python2.7）搭建起来以后，也以相同的参数运行，在同一个训练集上但是跑了多个batch，ssim和psnr都为0，这是为什么呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

感谢！已经解决
