### ISSUE TITLE
conv2d groups=1 

### ISSUE THREAD

**Issue by iperov** [hellloxiaotian/ESRGCNN#5]
groups=1 is default value and changes nothing from regular Conv2d()

**Comment by hellloxiaotian** [comment]
Dear Mr or Mrs,


This paper uses different channels to divide different group to mine relations of different channels in terms of depth and width to extract more robust features in image super-resolution. 


Best wishes,
Chunwei  
















At 2022-06-25 19:57:05, "iperov" ***@***.***> wrote:

groups=1 is default value and changes nothing from regular Conv2d()
